export const Z_INDEX = {
    globalNavigation: 999,
    mapFloatMenu: 9,
}

export const FONT = {
    pretendard: 'Pretendard',
};

const FONT_WEIGHT = {
    regular: 300,
    medium: 400,
    semiBold: 500,
    bold: 600,
    extraBold: 700,
    black: 800,
};

const LINE_HEIGHT = '140%';
const LETTER_SPACING = '0.03px';

export const TYPOGRAPHY = {
    Regular10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black10: {
        fontSize: '10px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black11: {
        fontSize: '11px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black12: {
        fontSize: '12px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black13: {
        fontSize: '13px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black14: {
        fontSize: '14px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black15: {
        fontSize: '15px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black16: {
        fontSize: '16px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black17: {
        fontSize: '17px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black18: {
        fontSize: '18px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black19: {
        fontSize: '19px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black20: {
        fontSize: '20px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black21: {
        fontSize: '21px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black22: {
        fontSize: '22px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black23: {
        fontSize: '23px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black24: {
        fontSize: '24px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black25: {
        fontSize: '25px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black26: {
        fontSize: '26px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black27: {
        fontSize: '27px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black28: {
        fontSize: '28px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black29: {
        fontSize: '29px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Regular30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.regular,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Medium30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.medium,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    SemiBold30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.semiBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Bold30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.bold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    ExtraBold30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.extraBold,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
    Black30: {
        fontSize: '30px',
        fontWeight: FONT_WEIGHT.black,
        lineHeight: LINE_HEIGHT,
        letterSpacing: LETTER_SPACING,
    },
} as const;

export const COLOR = {
    MonoWhite: '#FFFFFF',
    MonoBlack: '#000000',
    Gray50: '#F9FAFB',
    Gray100: '#F3F4F6',
    Gray200: '#E5E7EB',
    Gray300: '#C5CBD3',
    Gray400: '#9CA3AF',
    Gray500: '#6B7280',
    Gray600: '#4B5563',
    Gray700: '#374151',
    Gray800: '#1F2937',
    Gray900: '#111827',
    Gray950: '#1A1B1F',
    Green50: '#E8FBEC',
    Green100: '#B8F4C4',
    Green200: '#96EEA7',
    Green300: '#66E77F',
    Green400: '#48E266',
    Green500: '#1ADB40',
    Green600: '#18C73A',
    Green700: '#129B2D',
    Green800: '#0E7823',
    Green900: '#0B5C1B',
    Blue50: '#E8F5FF',
    Blue100: '#B8E0FF',
    Blue200: '#96D1FF',
    Blue300: '#66BDFF',
    Blue400: '#49B0FF',
    Blue500: '#1B9CFF',
    Blue600: '#198EE8',
    Blue700: '#136FB5',
    Blue800: '#0F568C',
    Blue900: '#0B426B',
    Red50: '#FFE9EC',
    Red100: '#FFBBC5',
    Red200: '#FF9AA9',
    Red300: '#FF6C82',
    Red400: '#FF506A',
    Red500: '#FF2445',
    Red600: '#E8213F',
    Red700: '#B51A31',
    Red800: '#8C1426',
    Red900: '#6B0F1D',
    PinkPrimary: '#FF4D86',
    PurplePrimary: '#A615F7',
    IndigoPrimary: '#1E1BFF',
    GreenPrimary: '#1ADB40',
    BluePrimary: '#1B9CFF',
    RedPrimary: '#FF2445',
    LablesPrimary: '#1A1B1F',
    LablesSecondary: '#374151',
    LablesTertiary: '#9CA3AF',
    LablesQuaternary: '#C5CBD3',
    LablesOpposition: '#FFFFFF',
    SurfaceLevel0: '#FFFFFF',
    SurfaceLevel1: '#F9FAFB',
    SurfaceLevel2: '#F3F4F6',
    SurfaceLevel3: '#E5E7EB',
    SurfaceLevel4: '#C5CBD3',
    GradientLinear: 'linear-gradient(90deg, #FF35F7 0%, #B600FF 46.5%, #1F1BFF 100%)'
} as const;

export const MEDIA_QUERY = {
    tablet: "screen and (min-width: 768px) and (max-width: 1199px)",
    mobile: "screen and (max-width: 767px)",
} as const;